### ISSUE TITLE
diagnoses not showing 

### ISSUE THREAD

**Issue by ph1l** [ph1l/ocemr#29]
still having some diagnoses not showing up when searching
for them, most notable one is "pregnancy"....even though it's in the
admin list, we can't choose it.

**Comment by kzcbum** [comment]
still need to add "Pregnancy" as searchable diagnosis. 

brute force review of admin level diagnoses available by Fellow found that all the listed diagnoses are available, we're just missing "Pregnancy" - I think this was W72?
