### ISSUE TITLE
Update test documentation

### ISSUE THREAD

**Issue by pochedls** [ph1l/ocemr#34]
I was trying to set some of this up for to see if I could get the web application running. 

@ph1l  - could you update some of the documentation based on your recent setup of a test server? 

Some of the issues I encountered: 
* util/make_version.sh does not exist
* Needed to install gpg (I am on a Mac)
* I got errors at: ./util/initialize_test_db.sh (see below)
    * eliminated many by downgrading to django v1.4 (used `conda create -n ocemr django sqlite matplotlib python=2.7` and then downgraded django using `pip install django==1.4`)
    * Missing source_data directory
    * Missing version (see error below)

> AttributeError: 'module' object has no attribute 'OCEMR_VERSION'

**Comment by ph1l** [comment]
I've never developed this on a mac, and don't know too much about operating in that environment. I can't guarantee that will work... The system is currently based on software versions available in an outdated and now unsupported release of debian (v6.0 - squeeze)

The easiest environment to setup a testing environment, most like what happens to be deployed in production now is on a debian squeeze virtual machine.

When I have time next, I will attempt to update the SETUP_TESTING doc where appropriate.

**Comment by pochedls** [comment]
Thanks @ph1l. I'd be happy to create a debian virtual machine, but I *think* some of the instructions would still not work, because it looked like some executables and source data was missing. I'm not sure, but it seems possible that you still might have to downgrade django from the apt-get install even using debian.

**Comment by ph1l** [comment]
That is true... This is all based on squeeze... so you'd need a now obsolete OS for everything to work out of the box. That being said I did just set up a "dev" environment on wheezy (using a digital ocean VM.)

**Comment by pochedls** [comment]
Hi @ph1l - I tried installing with a vagrant VM using debian wheezy. I realize a lot of the errors I got stemmed from a missing a closing `}` right [here](https://github.com/ph1l/ocemr/blob/master/settings.py.DIST#L20). Thanks for updating this documentation.

**Comment by ph1l** [comment]
Oh, I see..

**Comment by pochedls** [comment]
And - to be clear - I think that was the only change I had to make - the server is working.
