### ISSUE TITLE
scanning outside data

### ISSUE THREAD

**Issue by jfreem2** [ph1l/ocemr#40]
could a scanner option be incorporated? this would allow a scan of outside documents to tie to the chart. (requested by clinicians, but I believe the data size and complexity would be an issue)

**Comment by ph1l** [comment]
With the current hardware platform in production (containing a 4G disk,) saving image files is a non-starter... Perhaps with OCR we could save outside documents as text?

**Comment by kzcbum** [comment]
I think this was a visiting team feature request that is not reasonable. I would skip it for now.
