### ISSUE TITLE
Remove Immunizations and Vaccinations tabs

### ISSUE THREAD

**Issue by kzcbum** [ph1l/ocemr#41]
staff are not using these tabs and this would clean up space to have the Maternity tab

**Comment by ph1l** [comment]
@kzcbum The organization wants to completely delete the functionality and remove any existing data we currently have for inmmunizations and Vaccinations?

**Comment by kzcbum** [comment]
They are not using it at all. Wouldn't want to break anything by removing
those tabs, but leaving them and having a tab for maternity would extend
the options too far off screen for the smaller netbook workstations.

**Comment by ph1l** [comment]
they are not using it, so we will remove the interface and any data that exists in the database. I just wanted to explicitly clarify the existing data part.

**Comment by ph1l** [comment]
Merged
