### ISSUE TITLE
Add ANC visit # labels

### ISSUE THREAD

**Issue by kzcbum** [ph1l/ocemr#42]
for use with diagnosis and service tracking: Add "ANC 1", "ANC 2", "ANC 3", "ANC 4" and "ANC 5+" as diagnosis options for Maternity services

**Comment by ph1l** [comment]
Where can I get official descriptions to add to the (datafile)[https://github.com/ph1l/ocemr/blob/master/contrib/source_data/engeye/EngeyeEMRdx.csv]

ref: https://github.com/ph1l/ocemr/blob/master/util/import_dx_csv.py#L39

**Comment by kzcbum** [comment]
let me discuss with Bridget - this might be a moot point if the "Pregnancy" diagnosis option is available again. that's the true diagnosis. 
ICPC2 codes are what we based the background tags on, I'll look through those to clarify exact "official descriptions" for the named diagnoses.

**Comment by ph1l** [comment]
I just built the latest testing branch, and the Preganancy Diagnosis should be showing up now. You may need to clear your browser cache. `Shift`- reload.
