### ISSUE TITLE
Add Maternity tab

### ISSUE THREAD

**Issue by kzcbum** [ph1l/ocemr#43]
To allow for 1 page that tracks all pregnancy basics data, allowing data to be added onto with each subsequent pregnancy, so every "episode" of pregnancy does not require a new page, but this Maternity tab would be updated ongoing moving forward. This could also hold patient's past pregnancy data, as that would be entered at their pre-delivery antenatal care (ANC) visit for any past pregnancies.

This would summarize delivery related data and outcomes. Routine antenatal care visits would be under regular outpatient clinic visits, to allow for lab and med orders and billing per usual workflow. Admissions for labor and delivery would be tracked on paper until discharge, then discharge information to be entered per local standard format into a routine visit, with discharge summary information and meds/billing collected at the end. This would print as a normal clinic visit as their discharge summary.

Will attach sample page layout/data points of this Maternity Tab as an example.

**Comment by ph1l** [comment]
@kzcbum said:

> Will attach sample page layout/data points of this Maternity Tab as an example.

**Comment by kzcbum** [comment]
[Maternity tab mock-up.pdf](https://github.com/ph1l/ocemr/files/2236950/Maternity.tab.mock-up.pdf)

**Comment by kzcbum** [comment]
sorry, don't have way to fix the table using Drive options
