### ISSUE TITLE
Lab cancel button too close

### ISSUE THREAD

**Issue by kzcbum** [ph1l/ocemr#56]
Too easy to accidentally hit the cancel button for labs when trying to start results.
Similar issue with Undo-seen on patient queue. 
I can see how some orders or patients go “lost” or missing.
Is it possible to extend the space farther right to give them a bit more space?

**Comment by ph1l** [comment]
hmm, would adding an "are you sure" dialog be a better fix for some destructive actions?

My concern in adding space is that netbooks or old laptops may not have as much real estate to spare.

**Comment by kzcbum** [comment]
I think having a question stop like "Are you sure?" would work too.
